highlight: true

templates:
  GZMTU:
    reference: "gzmtu.docx"
    pandoc_filters:
      - "general.py"
    docx_handlers:
      GZMTU: {}
      first_line_indent:
        indent_size: 24
  # HUST:
  #   reference: "HUST.docx"
  #   pandoc_filters:
  #     - "general.py"
  #   docx_handlers:
  #     HUST: {}
  #     first_line_indent:
  #       indent_size: 24


